project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - finalproject.qmd

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Gabriel Fraguere
    right:
      - text: Pokémon Pokédex Analysis
        icon: dash-circle
        href: projects/finalproject.html
    tools: 
      
format:
  html:
    backgroundcolor: "#05054D"
    fontcolor: "aliceblue"
    linkcolor: "#30A9E6"
    mainfont: "sarif"
    fontsize: 17px
    theme: [cosmo, styles.scss]

